# Reenable dependabot after repo transfer
# https://github.com/dependabot/dependabot-core/issues/1923
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: 'next'
      - dependency-name: 'sharp'
