name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/dealmore/dealmore-build-images/lambdaci:nodejs12.x

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            .yarn
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Build
        run: |
          yarn --frozen-lockfile --cache-folder .yarn
          yarn workspace @dealmore/tf-next-image-optimization build

  test-integration:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/dealmore/dealmore-build-images/lambdaci:nodejs12.x

    services:
      s3:
        image: registry.gitlab.com/dealmore/dealmore-build-images:s3-emulator
        env:
          MINIO_ACCESS_KEY: test
          MINIO_SECRET_KEY: testtest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            .yarn
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Jest
        run: |
          yarn --frozen-lockfile --cache-folder .yarn
          yarn test
